from __future__ import annotations
from datetime import datetime
from pathlib import Path
from agents.debugger import DebugResult


class ReporterAgent:
    def build_pr_comment(
        self,
        run_results: dict,
        debug_results: list[DebugResult],
        coverage: dict | None = None,
        quality_scores: dict | None = None,
        mutation_reports: dict | None = None,
    ) -> str:
        passed = run_results.get("passed", 0)
        failed = run_results.get("failed", 0)
        skipped = run_results.get("skipped", 0)
        total = passed + failed + skipped
        pass_rate = round((passed / total) * 100) if total > 0 else 0
        duration = run_results.get("duration_seconds", 0)

        status_emoji = "✅" if failed == 0 else "❌"

        lines = [
            f"## {status_emoji} AITA Test Report",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Total Tests | {total} |",
            f"| Passed | {passed} ✅ |",
            f"| Failed | {failed} ❌ |",
            f"| Skipped | {skipped} ⏭️ |",
            f"| Pass Rate | {pass_rate}% |",
            f"| Duration | {duration:.1f}s |",
        ]

        if coverage:
            lines += [
                "",
                "### Coverage",
                "",
                "| Service | Lines | Branches | Functions |",
                "|---------|-------|----------|-----------|",
            ]
            for svc, cov in coverage.items():
                lines.append(
                    f"| {svc} | {cov.get('lines', 0):.1f}% | {cov.get('branches', 0):.1f}% | {cov.get('functions', 0):.1f}% |"
                )

        if quality_scores:
            lines += [
                "",
                "### Test Quality Scores",
                "",
                "| Test File | Grade | Score | Assertions | Coverage | Mutation |",
                "|-----------|-------|-------|------------|----------|---------|",
            ]
            for test_file, qs in quality_scores.items():
                name = Path(test_file).name
                lines.append(
                    f"| `{name}` | **{qs.grade}** | {qs.composite_score:.0f} "
                    f"| {qs.assertion_score:.0f} | {qs.branch_coverage:.0f}% "
                    f"| {qs.mutation_kill_rate:.0f}% |"
                )

        if mutation_reports:
            lines += [
                "",
                "### Mutation Testing",
                "",
                "| Source File | Score | Killed | Survived | Status |",
                "|------------|-------|--------|----------|--------|",
            ]
            for src_file, mr in mutation_reports.items():
                name = Path(src_file).name
                status = "✅ PASS" if mr.passed_threshold else "❌ FAIL"
                lines.append(
                    f"| `{name}` | {mr.mutation_score:.1f}% "
                    f"| {mr.killed} | {mr.survived} | {status} |"
                )

        if debug_results:
            lines += ["", "### Failure Analysis", ""]
            for dr in debug_results:
                confidence_badge = "🔴" if dr.confidence < 40 else "🟡" if dr.confidence < 75 else "🟢"
                lines += [
                    f"<details>",
                    f"<summary><b>{dr.test_name}</b> {confidence_badge} {dr.confidence}% confidence</summary>",
                    "",
                    f"**Root cause:** {dr.root_cause}",
                    "",
                    f"**Fix suggestion:** {dr.fix_suggestion}",
                ]
                if dr.fix_code:
                    lines += ["", f"```\n{dr.fix_code}\n```"]
                lines += ["", "</details>"]

        lines += [
            "",
            f"---",
            f"*Generated by [AITA](https://github.com) · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*",
        ]

        return "\n".join(lines)

    def build_summary_json(self, run_results: dict) -> dict:
        passed = run_results.get("passed", 0)
        failed = run_results.get("failed", 0)
        skipped = run_results.get("skipped", 0)
        total = passed + failed + skipped
        return {
            "total": total,
            "passed": passed,
            "failed": failed,
            "skipped": skipped,
            "pass_rate": round((passed / total) * 100, 1) if total > 0 else 0,
            "duration_seconds": run_results.get("duration_seconds", 0),
            "status": "passed" if failed == 0 else "failed",
        }
