import json
import logging
import os
import re
import sys
from pathlib import Path
from runners.base_runner import BaseRunner, RunResult

logger = logging.getLogger(__name__)

# Block shell injection characters; allow absolute paths (Windows/Unix)
_SHELL_INJECTION_RE = re.compile(r'[;|&`$()<>"\'\n\r]')
_TEST_EXT_RE = re.compile(r'\.(?:test|spec)\.[jt]sx?$')

# Names Jest searches for when no --config is given
_JEST_CONFIG_NAMES = (
    "jest.config.js", "jest.config.ts", "jest.config.mjs",
    "jest.config.cjs", "jest.config.cts", "jest.config.json",
)

# Minimal jest config written by AITA when the workspace has no jest setup
_AITA_JEST_CONFIG_NAME = "jest.aita.config.js"
_AITA_JEST_CONFIG_CONTENT = """\
/** Auto-generated by AITA — safe to delete after use */
module.exports = {
  testEnvironment: 'node',
  preset: 'ts-jest',
  transform: { '^.+\\\\.(ts|tsx)$': ['ts-jest', { diagnostics: false }] },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  transformIgnorePatterns: [],
  moduleDirectories: ['node_modules', '<rootDir>'],
  globals: { 'ts-jest': { tsconfig: { strict: false, esModuleInterop: true } } },
};
"""


class JestRunner(BaseRunner):
    def run(self, test_path: str, cwd: str = ".", **kwargs) -> RunResult:
        if _SHELL_INJECTION_RE.search(test_path) or not _TEST_EXT_RE.search(test_path):
            return RunResult(
                passed=0, failed=1, skipped=0,
                duration_seconds=0.0,
                output="",
                error=f"Unsafe test path rejected: {test_path!r}",
                exit_code=1,
            )

        # Determine which jest config to use.
        # If the workspace already has a jest config, let Jest find it automatically.
        # Otherwise point Jest at the AITA-generated config (written by node_setup_workspace).
        ws = Path(cwd)
        has_native_config = any((ws / name).exists() for name in _JEST_CONFIG_NAMES)
        aita_config = ws / _AITA_JEST_CONFIG_NAME

        if has_native_config:
            config_flags: list[str] = []
        elif aita_config.exists():
            config_flags = ["--config", str(aita_config)]
        else:
            # Last resort: write a minimal config inline and use it
            try:
                aita_config.write_text(_AITA_JEST_CONFIG_CONTENT, encoding="utf-8")
                config_flags = ["--config", str(aita_config)]
            except Exception:
                config_flags = []

        # Jest matches its positional argument as a regex against each test file's
        # absolute path.  On Windows, Python's tempfile returns 8.3 short names
        # (e.g. FKANZA~1) while Jest resolves the full long name (fkanzaoui), so
        # an absolute-path regex never matches.  Use a relative path from cwd instead —
        # it is a suffix of the absolute path regardless of short/long name form.
        try:
            jest_test_path = os.path.relpath(test_path, cwd).replace("\\", "/")
        except ValueError:
            # Different drives on Windows — fall back to basename-only pattern
            jest_test_path = Path(test_path).name
        # On Windows, npx is a .cmd file and is not resolved without shell=True
        cmd = ["npx", "jest", *config_flags, jest_test_path, "--json"]
        logger.debug("Jest cmd: %s  cwd=%s", cmd, cwd)
        stdout, stderr, exit_code = self._exec(cmd, cwd=cwd, shell=(sys.platform == "win32"))
        if exit_code != 0:
            logger.warning("Jest exit=%d stderr=%s", exit_code, (stderr or "").strip()[:400])

        try:
            report = json.loads(stdout)
            passed = report.get("numPassedTests", 0)
            skipped = report.get("numPendingTests", 0)

            # Suite-level execution errors (e.g. "Cannot find module 'vitest'") set
            # testExecError on the suite but leave numFailedTests=0 because no tests ran.
            # Collect those suites and surface their error messages.
            exec_error_suites = [
                r for r in report.get("testResults", [])
                if r.get("testExecError") or (r.get("status") == "failed" and not r.get("testResults"))
            ]
            exec_error_msgs = []
            for r in exec_error_suites:
                ee = r.get("testExecError") or {}
                msg = (ee.get("message") or ee.get("type") or "").strip()
                if msg:
                    exec_error_msgs.append(msg[:400])

            failed = report.get("numFailedTests", 0) + len(exec_error_suites)

            duration = sum(
                0 if r.get("testExecError") else
                sum(t.get("duration", 0) or 0 for t in r.get("testResults", []))
                for r in report.get("testResults", [])
            ) / 1000.0

            error_out = "; ".join(exec_error_msgs) if exec_error_msgs else (stderr if stderr else None)

        except (json.JSONDecodeError, KeyError, TypeError, ValueError):
            # TypeError  → stdout is None (npx/jest crashed before writing any output)
            # JSONDecodeError → Jest wrote non-JSON to stdout (config error, etc.)
            err_detail = stderr.strip() if stderr else (stdout or "no output")
            logger.warning("Jest JSON parse failed (exit=%d) — stderr: %s", exit_code, err_detail[:600])
            return RunResult(
                passed=0, failed=1, skipped=0,
                duration_seconds=0.0,
                output=stdout or "",
                error=f"Jest exited without JSON output (exit={exit_code}): {err_detail[:400]}",
                exit_code=exit_code,
            )

        return RunResult(
            passed=passed,
            failed=failed,
            skipped=skipped,
            duration_seconds=round(duration, 2),
            output=stdout,
            error=error_out,
            exit_code=exit_code,
        )
